name: partial_json_stream_parser
description: >-
  A Dart library for parsing partial and incomplete JSON strings, perfect for handling streaming JSON responses from LLMs and realtime APIs.
version: 1.0.0
repository: https://github.com/StiftTechnologies/partial_json_stream_parser
homepage: https://stift.com.br
publisher: stift.com.br
topics:
  - json
  - llm
  - streaming
  - ai

environment:
  sdk: ^3.6.2

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
